### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [Toni500github/customfetch#3]
I was just trying to establish your Android app as reproducible build. So close! It just has a small difference:

![Image](https://github.com/user-attachments/assets/811f2a79-6a07-4a95-8d79-bc0b5dad807f)

If the build-id could be removed, it would be RB! [Here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/Debug-failed-RBs#build-ids) are hints on how to establish that. Copying over:

>  for `cmake` ≥ 3.13, add this to `CMakeLists.txt`:

    add_link_options("-Wl,--build-id=none")

That would be your `android/CMakeLists.txt` then. Could you please do that? If you'd provide me an APK built after that change, and the commit it was built from, I'd verify it did the trick and worked out as expected – so your Android app could be marked as [Reproducible Build](https://reproducible-builds.org/).

For some background: At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). I was just about to see if we could add your app to the repo. Would be great if it could start as RB right away!

And if you're curious, we've also prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/RB-Hints-for-Developers) to help developers with that (plus some more documentation in the very same wiki).

Looking forward to your reply, and thanks in advance!

**Comment by BurntRanch** [comment]
Hello, thanks for bringing this to our attention!

This seems like an excellent idea, I don't see why not. I'll look into this a little further and will let you know about the results.

**Comment by Toni500github** [comment]
Hey there, sorry for the late time.
I've pushed a commit that indeed introduces this feature. The github articat is this: https://github.com/Toni500github/customfetch/actions/runs/14537417444/artifacts/2970423436

**Comment by Toni500github** [comment]
@IzzySoft Let me know for anything so that I can close this issue

**Comment by IzzySoft** [comment]
Thanks a lot! We'd need a release build, though (that seems to be a debug build). I've tried with the debug build, but:

```diff
  -rw-r--r--  0.0 unx  1634496 b-   634775 defN 1981-01-01 01:01:02 81df419d classes6.dex
- -rw-r--r--  0.0 unx  3178000 b-  3178000 stor 1981-01-01 01:01:02 0d1cb0cc lib/arm64-v8a/libcustomfetch.so
- -rw-r--r--  0.0 unx  1978452 b-  1978452 stor 1981-01-01 01:01:02 d5669c93 lib/armeabi-v7a/libcustomfetch.so
- -rw-r--r--  0.0 unx  3277388 b-  3277388 stor 1981-01-01 01:01:02 2a82a990 lib/x86/libcustomfetch.so
- -rw-r--r--  0.0 unx  3227368 b-  3227368 stor 1981-01-01 01:01:02 497e61bd lib/x86_64/libcustomfetch.so
+ -rw-r--r--  0.0 unx  3177760 b-  3177760 stor 1981-01-01 01:01:02 2fe1c9ca lib/arm64-v8a/libcustomfetch.so
+ -rw-r--r--  0.0 unx  1978212 b-  1978212 stor 1981-01-01 01:01:02 1b76b4f8 lib/armeabi-v7a/libcustomfetch.so
+ -rw-r--r--  0.0 unx  3277148 b-  3277148 stor 1981-01-01 01:01:02 d17a7a8d lib/x86/libcustomfetch.so
+ -rw-r--r--  0.0 unx  3227128 b-  3227128 stor 1981-01-01 01:01:02 4095caaa lib/x86_64/libcustomfetch.so
  -rw-r--r--  0.0 unx      909 b-      305 defN 1981-01-01 01:01:02 7a447283 assets/ascii/aix.txt
```

Diffoscope is rather huge (almost 5 MB). One part I was able to identify that we can fix on our end (the embedded build path). Another we can't (the embedded branch name: `customfetch·1.0.0·branch·main`with yours, `	customfetch·1.0.0·branch·HEAD` here). I guess much of this is due to additional debug info being embedded. I gladly try again with a release build, if you have one (and as there seems to be no `vcsInfo` embedded with the APK, please make sure to let me know the hash of the commit you've built that from then).

[diff_debug_1.zip](https://github.com/user-attachments/files/19814534/diff_debug_1.zip)

I've made a second run with the build path adjusted to what GitHub actions use (`/home/runner/work/<repoName>/<repoName>`), because I was curious how much of that difference might be caused by that. Not expecing it would be RB now (it isn't, due to all the debug stuff inside) – but as expected, size of the Diffoscope output is much smaller, down to about 1 MB then:

[diff_debug_2.zip](https://github.com/user-attachments/files/19814568/diff.zip)

Apart from the branch names, and a bunch of offsets being "shifted", I was surprised to find this:

![Image](https://github.com/user-attachments/assets/f447682d-1e8c-41f9-95a3-a9f9cded0988)

Maybe debug builds enforce it? Guess we can tell once we could compare a release build…

**Comment by Toni500github** [comment]
Oh, I thought you were using the debug build from either the artifacts or compiled from source, from the latest commit, so that's why I sent a debug build. I'll be glad to send a release build from the v1.0 branch tag that I'll compile without the build-id.

Is this what you need?

**Comment by IzzySoft** [comment]
Close. Or yes. Depends on how you mean it. What I need is a release APK built with the change, from a clean tree (so no local changes or artifacts remaining from previous builds) – and the hash of the commit you've built that from.

What happens then: I build from the very same commit, then use `apksigcopier` to copy over your signature. The result should then be a byte-identical APK – which signals "reproducible". Not byte-identical – not reproducible. So the goal is that I (or anyone else) can reproduce your build and get the exact same APK.

Which, in laymen's terms, means: "yes, that was indeed built from the source it claims to, nothing added or removed" (while a "fail" does not necessarily mean "something added or removed", as we've just seen – it's like "when you've walked through the rain, you are wet – but when you are wet, you've not necessarily walked through the rain" 😉 ).

**Comment by Toni500github** [comment]
ok so I kind of followed the instructions you gave in the 1st message
> [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/RB-Hints-for-Developers)

so I checkout the tag v1.0.0, applied these patches:
```patch
diff --git a/android/CMakeLists.txt b/android/CMakeLists.txt
index 75319c8..1751656 100644
--- a/android/CMakeLists.txt
+++ b/android/CMakeLists.txt
@@ -19,6 +19,7 @@ file(GLOB
 )
 
 add_library(customfetch SHARED ${SRC})
+add_link_options("-Wl,--build-id=none")
 
 # get git branch
 execute_process(
diff --git a/android/app/build.gradle.kts b/android/app/build.gradle.kts
index 7612ee4..e407d9a 100644
--- a/android/app/build.gradle.kts
+++ b/android/app/build.gradle.kts
@@ -37,6 +37,8 @@ android {
                 targets("customfetch")
             }
         }
+        // disable generating PNGs from vector drawables
+        // commenting because it's a val
+        //vectorDrawables.generatedDensities = []
     }
 
     signingConfigs {
@@ -70,6 +72,8 @@ android {
                 getDefaultProguardFile("proguard-android-optimize.txt"),
                 "proguard-rules.pro"
             )
+            // disable PNG crunching
+            isCrunchPngs = false
         }
     }
```

and the run the command `./gradlew clean assembleRelease --no-build-cache --no-configuration-cache --no-daemon`
Here's the apk release I built: 
[app-release.apk.zip](https://github.com/user-attachments/files/19814926/app-release.apk.zip)

**Comment by IzzySoft** [comment]
Well, that's not what the instruction there says:

> Always build the APK from exactly the commit your release-tag will point to!

"from exactly the commit" – not "from the commit and some patches applied" 😉 The build here runs in an ephemeral container – and applying patches is not happening there (the container basically just gets that "config" to process it). To make it easier to understand, here's what the current build recipe for customFetch looks like:

```yaml
---
repository: https://github.com/Toni500github/customfetch.git
updates: releases
versions:
  - tag: v1.0.0
    apks:
      - apk_pattern: customfetch-android-app-.*\.apk
        apk_url: https://github.com/Toni500github/customfetch/releases/download/v1.0.0/customfetch-android-app-v1.0.0.apk
        build:
          - cd android
          - sed -r '/signingConfigs.getByName/d' -i app/build.gradle.kts
          - ./gradlew assembleRelease
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /home/runner
        build_repo_dir: /home/runner/work/customfetch/customfetch
        build_timeout:
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

It's an automated run inside a podman container. I don't have a "local build env" I could try your manual approach on, sorry 😢

I guess you applied the above changes and committed them? **For a manual check as we're doing it here now,** can you build a release APK from that commit, and give me that APK together with the commit hash? Then I can override the commit hash of that recipe, and compare the result against your APK. The above "first basic rule" applies to the release process, not to manual checks like here. It's so that recipes can be updated automatically. For a manual check, we can take **any commit** – it just needs to be a "clean tree without manual changes or remaining artifacts".

**Comment by IzzySoft** [comment]
> So I'll commit that patch I sent, then I'll build in a brand new cloned repo with the same command. Is that ok?

That sounds perfect! Now let's see how it turned out…

Strange, the `.so` again differ. Diff got smaller by ~200 kB, though. I don't get it: build-id is still in there – but checking the code at the commit, your `android/CMakeList.txt` has the line to disable it. And none of the other differences have been there with my initial build (before I opened this issue).

[diff.zip](https://github.com/user-attachments/files/19816542/diff.zip)

There also seem some ordering issues now:

![Image](https://github.com/user-attachments/assets/6ebf5dfb-3bfc-4937-bea8-e0de95301e3c)

(saw them in the previous build, too – but not in the initial one)

Apologies for bothering you so much here – it looked like a simple fix initially. I have no clue what causes the ordering differences in the `.so` files – especially as it hasn't been there at the beginning. Concerning some of the additional details, maybe [this](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/Debug-failed-RBs#clang) can help? Walking your commit history (what changed since the release build), I see you switched to a newer Ubuntu for the image. And looking at your GH action again, you use `make` while I've used `gradlew` directly. So let me try that… Nope, makes no difference: I get the very same APK I got on the previous run.

**Comment by Toni500github** [comment]
@IzzySoft Sorry for the late response, I had a busy day so that's why I couldn't reply.

> Apologies for bothering you so much here

Don't worry, I should be the one apologizing for being kind of dumb because it's first time I have ever recieved an issue like this.

I think it all started since I pushed c73c036615035f55cc3e0ea80c746e214c72f7a5 [project: add macos support (some things WIP)](https://github.com/Toni500github/customfetch/commit/c73c036615035f55cc3e0ea80c746e214c72f7a5) until on. When you created this issue, I believe we were in 3e9707248f860597101236cbbb37b29539933ae2 [makefile: separete install from install-common](https://github.com/Toni500github/customfetch/commit/3e9707248f860597101236cbbb37b29539933ae2) which is also the parent of the previous I metioned above.

You say:
> I was just trying to establish your Android app as reproducible build. So close! It just has a small difference:
> If the build-id could be removed, it would be RB! [Here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/Debug-failed-RBs#build-ids) are hints on how to establish that. Copying over:

So I think you could try out using the commit 3e9707248f860597101236cbbb37b29539933ae2 [makefile: separete install from install-common](https://github.com/Toni500github/customfetch/commit/3e9707248f860597101236cbbb37b29539933ae2) and apply the cmake line
```cmake
add_link_options("-Wl,--build-id=none")
```
And try if it fixes everything

**Comment by IzzySoft** [comment]
> So I think you could try out using the commit https://github.com/Toni500github/customfetch/commit/3e9707248f860597101236cbbb37b29539933ae2 [makefile: separete install from install-common](https://github.com/Toni500github/customfetch/commit/3e9707248f860597101236cbbb37b29539933ae2) and apply the cmake line (even with sed)

That won't match your APK then. We need a bit-identical result here.

> I want you to do this because then it would be kind of difficult to track down why it builds different on some machines

I gladly help debugging that! Here's my suggestion of how it could work – if it's OK with you:

* create a (temporary) branch off the commit the last release was built from (the one that was "so close")
* add and commit the changes you see fit
* build an APK from a clean tree (i.e. no local changes, no artifacts left from previous builds) at that commit
* provide me that APK (e.g. rename it to `*.zip` and attach it here – Github doesn't accept `*.apk` directly for some funny reason) and its commit hash
* I build and compare against that
* based on the outcome, we can see how to proceed

Would that work for you?

**Comment by Toni500github** [comment]
Aight sure, on it with `./gradlew clean assembleRelease --no-build-cache --no-configuration-cache --no-daemon`

**Comment by Toni500github** [comment]
@IzzySoft
The app (rename to .apk): [app-release.zip](https://github.com/user-attachments/files/19822982/app-release.zip)

branch: temp
commit: cf07f36794c6268ba8b9ca6804ac53070c6514b4

**Comment by IzzySoft** [comment]
Running now. Good idea to add the linker options to **all** `‎CMakeLists.txt` files!

Hm, not RB – `*.so` differ. Running Diffoscope now to figure out where and what… wtf? Still build-ids:

![Image](https://github.com/user-attachments/assets/e73e24ae-5b04-43dd-a379-dec133f6bcf9)

and the branch name. Do you really need to embed that? And why does that information appear at different positions? The diff again is more than 1 MB, but most of it is "shifted offsets" due to that branch information being at different positions.

[diff.zip](https://github.com/user-attachments/files/19823080/diff.zip)

That's totally unexpected. Going by [the difference of the commits](https://github.com/Toni500github/customfetch/compare/v1.0.0...cf07f36794c6268ba8b9ca6804ac53070c6514b4), only changes were the linker options, an update to the Readme (which we can ignore here), and some changes to the Makefile (which should have no effect here either, as they also concern install, not build). Leaves me clueless, to be honest…

Hm, shouldn't really matter but who knows: except for the release APK, were all the other APKs I've tried built using your GH action – or locally on your machine? I don't see any path mentioned in the diffoscope, so I assume it's not that. But if you did **not** build with the GitHub CI, can you name the path your sources were checked out to? Here it was `/home/runner/work/customfetch/customfetch` to match the CI.

**Comment by Toni500github** [comment]
> and the branch name. Do you really need to embed that?

It's not only the branch name, but also the version that's also fundamental. But maybe I can cross it off if it's on the android app.

At the same time though, if it's possible to avoid it's better, because there is no need to `git checkout` since it's the latest commit of that branch and you can easily build it to have the branch name instead of HEAD

> were all the other APKs I've tried built using your GH action – or locally on your machine?

All the APKs I have sent here were all built on my main PC, meanwhile the release v1.0.0 was built with GH actions.
I suppose when you opened this issue, you were using the release from GH actions and if I added the linker option before the release, maybe it would've been all fixed.

**Comment by Toni500github** [comment]
I have a good plan:
- Create a temporary private repo
- Add the linker option on **all** build systems
- GH actions creates the release and you can test it out

**Comment by Toni500github** [comment]
@IzzySoft

private repo: https://github.com/Toni500github/customfetch-temp/ (check for any inviations)
zip source code if you don't want to clone: [customfetch-temp-temp.zip](https://github.com/user-attachments/files/19825476/customfetch-temp-temp.zip)
temponary release apk from the repo: [customfetch-android-app-temp.zip](https://github.com/user-attachments/files/19825473/customfetch-android-app-temp.zip)

Don't checkout any commits, the branch `temp` is the main one in

**Comment by IzzySoft** [comment]
> because there is no need to git checkout since it's the latest commit of that branch and you can easily build it to have the branch name instead of HEAD

That only works here at tag level (the framework here is intended to check releases) – which also implies that APKs must be built from a clean tree at the commit the tag points to. As soon as we need to switch to a different branch/commit, it's a `git checkout <hash>`. I've never tried to specify a branch name for a tag, though. For testing, that might work (for releases not).

> All the APKs I have sent here were all built on my main PC, meanwhile the release v1.0.0 was built with GH actions.

That explains! Thanks!

> I suppose when you opened this issue, you were using the release from GH actions and if I added the linker option before the release, maybe it would've been all fixed.

That's my guess, too.

> I have a good plan:

That sounds good! If that private repo is a fork of the original, the resulting APK should be compatible to this one here (if it's the same commit of course). I cannot build from a private repo, though, as builds happen in an ephemeral container here and not with any credentials (and I see no way to clone the private repo to build from that local clone, as the container would not see that either). So I could build from here, but compare against the APK from there. But that also means:

> Don't checkout any commits, the branch `temp` is the main one in the repo

We don't have that branch here, so that would not work. Can you create it here, with the same commit? I'd then try specifying the branch instead of a tag (I'm now curios if that indeed works), and once we're done the branch can be dropped.

Grmpf. I've just looked at the commit history in both repos, that won't work, they are different. Would it be a big problem to make that temp repo public for our test? Then I could build from that directly, and we could even tag there and whatever is needed, without messing up the main repo.

**Comment by Toni500github** [comment]
> Would it be a big problem to make that temp repo public for our test?

Not really, but the reason I did in a private repo is because I didn't want to flood the explore tab for who follows me of useless customfetch releases. But just for the sake of testing, I made it public now

**Comment by IzzySoft** [comment]
😢 

![Image](https://github.com/user-attachments/assets/5a87305d-750b-41b0-8aae-8df3d782f832)

This was the recipe:

```yaml
---
repository: https://github.com/Toni500github/customfetch-temp.git
updates: releases
versions:
  - tag: temp
    apks:
      - apk_pattern: customfetch-android-app-.*\.apk
        apk_url: https://github.com/Toni500github/customfetch-temp/releases/download/temp/customfetch-android-app-temp.apk
        build:
          - cd android
          - sed -r '/signingConfigs.getByName/d' -i app/build.gradle.kts
          - ./gradlew assembleRelease
          - find . -name '*.apk'
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /home/runner
        build_repo_dir: /home/runner/work/customfetch/customfetch
        build_timeout:
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

**Comment by Toni500github** [comment]
Sorry for my french
This is some weird bullshit 

I have added the link option everywhere and still it has it?? Also why tf is the version doing in a different place? 

Ok so I was currently working on a new version displaying, which is basically depending on the commit instead of branch. **Maybe** I should make that for Android app only, it displays just the version.

For the linker build id, maybe I should investigate more about disabling it. Can you please tell how you check the diffs and check  if it has the build id or not?

**Comment by IzzySoft** [comment]
> I have added the link option everywhere and still it has it??

That's what confuses me most here.

> Also why tf is the version doing in a different place?

Wish I knew…

> Can you please tell how you check the diffs and check if it has the build id or not?

If you want to play with the rebuilder framework yourself: [rbuilder_setup](https://codeberg.org/IzzyOnDroid/rbuilder_setup) sets up everything for you within less than 5 minutes, including the tools to debug. For debugging failed RBs, we've set up a wiki with instructions: [Debug failed RBs](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/Debug-failed-RBs). Be welcome to ask should you get stuck (or have questions otherwise).

For the build-id, that's usually shown with Diffoscope output (which is also what my screenshots are from).

**Comment by IzzySoft** [comment]
temp v1.0.0 is RB! 🥳 

```yaml
  {
    "upstream_signed_apk_sha256": "d933893b08573d4d3b2dbcd5e1f01aad454468d8e6ad52744291f7e8fe8069d8",
    "built_unsigned_apk_sha256": "d7ee2bbb87b346bbbcce275915d1fbe4dda1b2820288d09f73d78409fc1adb99",
    "signature_copied_apk_sha256": "d933893b08573d4d3b2dbcd5e1f01aad454468d8e6ad52744291f7e8fe8069d8"
  }
```

What did the trick?
